### ISSUE TITLE
Decide Wiki

### ISSUE THREAD

**Issue by PabloAceG** [PabloAceG/server-monitoring#9]
Look for a private documentation solution to register ports, debugging, etc.

- Confluence
- Hugo
- MediaWiki
- Nikola

Should consider:
- Open-Source
- Version control system
- Can edit docs using terminal (emacs, vim, etc.)

**Comment by PabloAceG** [comment]
- Confluence is not open-source, so discarded
- Hugo has nice aesthetics, as well as having an Emacs plugin as well as being extensible
- MediaWiki is nice, altough it's too "simplistic" in aesthetic compared to Hugo, for example
- Nikola is similar to Hugo (at first glance)

Could also include XWiki, similar to Hugo and Nikola

**Comment by PabloAceG** [comment]
XWiki cannot be used, as it seems not to allow file edition using terminal. 
@ZenTauro suggest `mkdocs` and `nikola` seems to be out of the discussion.

Contestants:
- Hugo
- mkdocs

**Comment by ZenTauro** [comment]
I've seen that Material MkDocs can work nicely with markdown and has a
lot of interesting features

**Comment by PabloAceG** [comment]
Final decision:
[Wiki.js](https://js.wiki/)

1. Allows for git as version control system
2. Open-source
3. Allows many technologies for deployment
4. Can edit using Vim/Emacs - writing Markdown
